export const navigationItems = [
  { to: '/', label: '工作台', icon: 'Home', hasSub: false },
  { to: '/bi', label: 'BI分析', icon: 'Chart', hasSub: true },
  { to: '/profile', label: '个人中心', icon: 'UserIcon', hasSub: false },
  { to: '/tenant', label: '租户配置', icon: 'Settings', hasSub: true },
  { to: '/org', label: '组织管理', icon: 'Layers', hasSub: false },
  { to: '/users', label: '用户管理', icon: 'Users', hasSub: false },
  { to: '/roles', label: '角色管理', icon: 'Users', hasSub: false },
  { to: '/menus', label: '菜单管理', icon: 'Layers', hasSub: false },
  { to: '/dict', label: '字典管理', icon: 'FileText', hasSub: false },
  { to: '/announcements', label: '公告管理', icon: 'Bell', hasSub: false },
  { to: '/logs', label: '系统日志', icon: 'CheckCircle', hasSub: true },
  { to: '/monitor', label: '系统监控', icon: 'Activity', hasSub: false },
  { to: '/messages', label: '消息中心', icon: 'Clock', hasSub: false },
  { to: '/sysconfig', label: '系统设置', icon: 'Settings', hasSub: false },
] as const;
